CREATE SEQUENCE REM_API_TRACE_SEQ
	MINVALUE 1
	MAXVALUE 99999999999
	START WITH 1
	INCREMENT BY 1
	CACHE 500 
	CYCLE
ORDER ;

CREATE SEQUENCE REM_API_TRACE_TRAN_NO_SEQ
	MINVALUE 1
	MAXVALUE 99999999999
	START WITH 1
	INCREMENT BY 1
	CACHE 500 
	CYCLE
ORDER ;


CREATE TABLE REM_API_TRACE
(
  ID                      		NUMBER(19) NOT NULL,
  EXCHANGE_CODE					VARCHAR2(16),
  USER_ID						VARCHAR2(20),
  PIN_NO					    VARCHAR2(40),
  IP_ADDRESS					VARCHAR2(32),
  REQ_TYPE					    VARCHAR2(32),
  STATUS						VARCHAR2(32),
  CBS_DATE					    DATE NOT NULL,
  TRAN_NO						VARCHAR2(48),
  EX_TRAN_ID					VARCHAR2(48),
  REQUEST_MSG		           	CLOB,
  RESPONSE_MSG		           	CLOB,
  BRANCH_CODE				    NUMBER(8),
  CANCEL_STATUS	 				VARCHAR2(32),
  CBS_SETTLEMENT_STATUS			VARCHAR2(1),
  CBS_BATCH_INFO			    VARCHAR2(48),
  TRY_COUNT						NUMBER(3) DEFAULT 0,
  CREATION_DATE_TIME			DATE DEFAULT SYSDATE,
  PRIMARY KEY (ID)
);

CREATE INDEX IDX01_REM_API_TRACE ON REM_API_TRACE(REQ_TYPE, STATUS, CANCEL_STATUS);
CREATE INDEX IDX02_REM_API_TRACE ON REM_API_TRACE(TRAN_NO);


